### ISSUE TITLE
Errors when run examples

### ISSUE THREAD

**Issue by itewqq** [SoftSec-KAIST/Reassessor#1]
Hi, I've followed the instructions in the [readme](https://github.com/SoftSec-KAIST/Reassessor/tree/main#example), but error occurs:

```sh
(reasm) [itemqq@itemqq-arch Reassessor]$ python --version
Python 3.8.16
(reasm) [itemqq@itemqq-arch Reassessor]$ python -m reassessor.preprocessing ./example/bin/hello ./output
[+] docker run --rm -v /home/itemqq/fault/Reassessor/output/bin:/input -v /home/itemqq/fault/Reassessor/output/reassem:/output reassessor/retrowrite:613562 sh -c "python3 -m retrowrite.librw_x64.rw /input/hello /output/retrowrite.s"
Unable to find image 'reassessor/retrowrite:613562' locally
613562: Pulling from reassessor/retrowrite
e706e0a9f423: Pull complete 
67067e559e33: Pull complete 
Digest: sha256:f5679d9e2bdf521b561698a843dae655cda88aca6f5ce943deec585335c0054d
Status: Downloaded newer image for reassessor/retrowrite:613562
I NEED SOMEBODY HELP
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/retrowrite/librw_x64/rw.py", line 1045, in <module>
    loader.load_functions(flist)
  File "/retrowrite/librw_x64/loader.py", line 68, in load_functions
    print(func.__dict__)
AttributeError: 'NoneType' object has no attribute '__dict__'
```

Any suggestions on this issue?

**Comment by witbring** [comment]
Hi, @itewqq. Thanks for the report.

The problem is caused by RetroWrite when it reassembles the example binary. 
I have examined [source code](https://github.com/witbring/retrowrite/blob/master/librw_x64/loader.py#L68), and concluded that RetroWrite misses the function even it was registered in .init_array section. 
However, I am not sure the exact reason. I need more information about your binary.
Could you dump .init_array section and function symbols in your binary?

- dump the contents of .init_array
$ objdump -s -j .init_array ./example/bin/hello

- list function symbols
$ readelf -s ./example/bin/hello | grep FUNC

**Comment by itewqq** [comment]
@witbring The experiment machine producing this error is unavailable for me until next week, I'll give the dump contents when I get it.

I didn't make any changes after cloned the repo,  don't know if python=3.8 matters or not.

**Comment by itewqq** [comment]
@witbring 

- dump the contents of .init_array
```sh
$ objdump -s -j .init_array ./example/bin/hello

./example/bin/hello：     File format elf64-x86-64

Contents of section .init_array:
 3dc0 30110000 00000000                    0....... 
```
- list function symbols
```sh
$ readelf -s ./example/bin/hello | grep FUNC
     1: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _[...]@GLIBC_2.34 (2)
     3: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND [...]@GLIBC_2.2.5 (3)
     6: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND [...]@GLIBC_2.2.5 (3)
     6: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __libc_start_mai[...]
    12: 0000000000001220     0 FUNC    GLOBAL HIDDEN    16 _fini
    13: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND printf@GLIBC_2.2.5
    18: 0000000000001140   119 FUNC    GLOBAL DEFAULT   15 foo
    20: 0000000000001040    38 FUNC    GLOBAL DEFAULT   15 _start
    22: 00000000000011c0    93 FUNC    GLOBAL DEFAULT   15 main
    25: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize@G[...]
    26: 0000000000001000     0 FUNC    GLOBAL HIDDEN    13 _init
```

**Comment by witbring** [comment]
Hi, @itewqq 

I think one intrinsic function (like frame_dummy) may be located in 0x1130, but the static linker in your machine may omit the function symbol for some reasons.
Hmm, I'm curious about your running environment. If it's ok please let me know.

In addition, I have checked the latest [RetroWrite](https://github.com/HexHive/retrowrite) and found [the same code routine](https://github.com/HexHive/retrowrite/blob/master/librw_x64/loader.py#L68).
Thus, we could not resolve the issue right now, since RetroWrite is designed to refer function symbols. 
If you want to fix it, please report the issue at [RetroWrite](https://github.com/HexHive/retrowrite).

Instead, you can run our example without RetroWrite as follows:
```
$ python3 -m reassessor.preprocessing ./example/bin/hello ./output --no-retrowrite
$ ls ./output/reassem
ddisasm.s
```

Then, you can run Reassessor with Ddisasm-generated code.
```
$ python3 -m reassessor.reassessor ./example/bin/hello ./example/asm ./output  \
  --ddisasm ./output/reassem/ddisasm.s
$ ls ./output/norm_db
ddisasm.db  gt.db
$ ls ./output/errors/ddisasm
disasm_diff.txt  sym_diff.txt  sym_errors.dat  sym_errors.json
```
